services:
  db:
    # IMAGEM ATUALIZADA PARA POSTGRESQL 16
    image: postgres:16-alpine
    container_name: janela_nova-db-1
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    environment:
      POSTGRES_DB: ${DB_NAME}
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
    ports:
      - "5432:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U $$POSTGRES_USER -d $$POSTGRES_DB"]
      interval: 5s
      timeout: 5s
      retries: 5
    restart: always

  web:
    build: .
    container_name: janela_nova-web-1
    command: >
      bash -c "python manage.py runserver 0.0.0.0:8002"
    volumes:
      - .:/code
    ports:
      - "8002:8002"
    env_file:
      - .env
    depends_on:
      db:
        condition: service_healthy
    restart: always

volumes:
  postgres_data: