"""
Django settings for app project.

Generated by 'django-admin startproject' using Django 5.0.6.

For more information on this file, see
https://docs.djangoproject.com/en/5.0/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.0/ref/settings/
"""
import os
from pathlib import Path
import environ




# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent

# --- Django-environ (.env) ---
env = environ.Env(DEBUG=(bool, False))
environ.Env.read_env(BASE_DIR / ".env")


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/5.0/howto/deployment/checklist/

SECRET_KEY = 'django-insecure-your-secret-key-here'
DEBUG = True

ALLOWED_HOSTS = []


# Application definition

INSTALLED_APPS = [
    'jazzmin',
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'inova',
]

# Configurações do tema Jazzmin para estilização do Django Admin
JAZZMIN_SETTINGS = {
    "site_title": "Janela de Ideias",
    "site_header": "Janela de Ideias",
    "site_brand": "Janela de Ideias",
    "welcome_sign": "Bem-vindo ao painel Janela de Ideias",
    "copyright": "Janela de Ideias",
    
    # LOGO personalizada
    "site_logo": "images/janela.png",  # coloque o arquivo em static/img/logo_janela.png
    "site_brand": "Janela de Ideias",

    # Tema de cores
    "theme": "flatly",  # base leve
    "dark_mode_theme": None,

    "login_template": "admin/login.html",
    # Ordem do menu (como na imagem-alvo)
    "order_with_respect_to": ["inova.Startup", "inova.Noticia", "inova.LinkFormulario", "auth"],

    # Ícones da barra lateral (Bootstrap Icons)
    "icons": {
        "auth": "bi bi-people-fill",
        "auth.User": "bi bi-person-fill",
        
        "inova.Startup": "bi bi-rocket-takeoff-fill",
        "inova.Noticia": "bi bi-newspaper",
        "inova.LinkFormulario": "bi bi-file-earmark-text-fill",
    },
}

JAZZMIN_SETTINGS["custom_css"] = "css/custom_admin.css"

JAZZMIN_UI_TWEAKS = {
    "theme": "flatly",  
    "dark_mode_theme": None,
    "navbar_small_text": False,
    "footer_small_text": False,
    "body_small_text": False,
    "brand_small_text": False,
    "accent": "primary",  
    "navbar": "bg-white",
    "navbar_fixed": True,
    "sidebar": "bg-primary", # Deixa a barra lateral azul
    "accent": "accent-primary",
    "sidebar_fixed": True,
    "sidebar_text": "text-white", # Texto da barra lateral branco
    "show_ui_builder": False,
    
    # ISSO É O QUE FORÇA AS CORES AZUIS NO DASHBOARD E NO SIDEBAR,
    # SEM AFETAR A TELA DE LOGIN.
    "theme": "flatly", # O tema flatly é o azul/branco
    "dark_mode_theme": None, # Desativa o modo escuro
    
    # Cores da barra superior e lateral
    "navbar": "navbar-white", # Barra superior branca
    "sidebar": "sidebar-dark-primary", # Barra lateral azul escura
    "sidebar_nav_child_indent": True, # Indentação para sub-menus
    
    # Fixa as barras
    "navbar_fixed": True,
    "sidebar_fixed": True,
    
    "show_ui_builder": False, # Esconde o construtor de UI
    
}

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'app.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [BASE_DIR / 'templates'],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'app.wsgi.application'


# Database
DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.postgresql',
        'NAME': 'janela_ideias',
        'USER': 'postgres',
        'PASSWORD': '12345',
        'HOST': 'db',
    }
}

# corrção de domininio no deploy
# Informa ao Django para confiar no cabeçalho 'X-Forwarded-Host' vindo do proxy (Apache)
USE_X_FORWARDED_HOST = True

# Esta é a linha mais importante:
# Define o prefixo do caminho onde a aplicação está sendo servida.
FORCE_SCRIPT_NAME = "/janeladeideias"


# Password validation
# https://docs.djangoproject.com/en/5.0/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/5.0/topics/i18n/

LANGUAGE_CODE = 'pt-br'

TIME_ZONE = 'America/Sao_Paulo'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.0/howto/static-files/

STATIC_URL = '/janeladeideias/static/'

# Diretórios onde Django deve procurar arquivos estáticos adicionais
STATICFILES_DIRS = [
    BASE_DIR / "static",
]

# Diretório onde os arquivos estáticos serão coletados para produção
STATIC_ROOT = BASE_DIR / 'staticfiles'
# Default primary key field type
# https://docs.djangoproject.com/en/5.0/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'


CORS_ALLOW_ALL_ORIGINS = True # Permite que qualquer domínio acesse a API

ALLOWED_HOSTS = ['*']
CSRF_TRUSTED_ORIGINS = [
    'https://inovaufpi.ufpi.br'
]


MEDIA_ROOT = os.path.join(BASE_DIR, 'media')
MEDIA_URL = '/media/'


# DEBUG
"""LOGGING = {
    'version': 1,
    'disable_existing_loggers': False,
    'handlers': {
        'console': {
            'class': 'logging.StreamHandler',
        },
    },
    'root': {
        'handlers': ['console'],
        'level': 'DEBUG',
    },
    'loggers': {
        'django': {
            'handlers': ['console'],
            'level': 'DEBUG',
            'propagate': True,
        },
    },
}"""
