# Generated by Django 5.0.6 on 2024-06-04 00:40

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='startup',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('nome', models.CharField(max_length=200)),
                ('cnpj', models.IntegerField(max_length=14)),
                ('area_de_negocio', models.CharField(max_length=200)),
                ('setor', models.CharField(max_length=200)),
                ('email', models.CharField(max_length=200)),
                ('telefone', models.IntegerField()),
            ],
        ),
    ]
