# Generated by Django 5.2.6 on 2025-09-30 19:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Startup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome_startup', models.CharField(max_length=100)),
                ('sobre_a_startup', models.TextField()),
                ('como_UFPI_contribuiu', models.TextField(blank=True, null=True, verbose_name='Como a UFPI contribuiu?')),
                ('ano_fundacao', models.IntegerField(default=0, verbose_name='Ano de Fundação')),
                ('setor_atuacao', models.CharField(max_length=100, verbose_name='Setor de Atuação')),
                ('tamanho_equipe', models.CharField(max_length=100, verbose_name='Tamanho da Equipe')),
                ('incubadora', models.CharField(blank=True, max_length=100)),
                ('logo_startup', models.ImageField(blank=True, null=True, upload_to='logos_startups/')),
            ],
        ),
        migrations.CreateModel(
            name='RedesSociais',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('linkedin', models.URLField(blank=True, null=True)),
                ('facebook', models.URLField(blank=True, null=True)),
                ('instagram', models.URLField(blank=True, null=True)),
                ('twitter', models.URLField(blank=True, null=True)),
                ('startup', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='redes_sociais', to='inova.startup')),
            ],
        ),
        migrations.CreateModel(
            name='MembroEquipe',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome_membro', models.CharField(max_length=100, verbose_name='Nome do Membro')),
                ('funcao_membro', models.CharField(max_length=100, verbose_name='Função')),
                ('foto_membro', models.ImageField(blank=True, null=True, upload_to='fotos_membros/')),
                ('startup', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='membros', to='inova.startup')),
            ],
        ),
        migrations.CreateModel(
            name='Contato',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email_startup', models.EmailField(max_length=254, verbose_name='E-mail')),
                ('telefone_startup', models.CharField(max_length=20, verbose_name='Telefone')),
                ('site_startup', models.URLField(blank=True, null=True, verbose_name='Site')),
                ('startup', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='contato', to='inova.startup')),
            ],
        ),
    ]
