# Generated by Django 5.0.7 on 2024-08-13 17:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Noticias',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('nome', models.CharField(max_length=200)),
                ('descricao', models.TextField(default='Descricao')),
                ('imagem', models.ImageField(blank=True, null=True, upload_to='media/noticias/')),
                ('link', models.URLField(blank=True, null=True)),
                ('data', models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name='Startup',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('nome', models.CharField(max_length=200)),
                ('descricao', models.TextField(default='descrição...')),
                ('cnpj', models.IntegerField()),
                ('area_de_negocio', models.CharField(max_length=200)),
                ('setor', models.CharField(max_length=200)),
                ('email', models.CharField(max_length=200)),
                ('telefone', models.IntegerField()),
                ('logo_startup', models.ImageField(blank=True, null=True, upload_to='inova/')),
                ('rua', models.CharField(blank=True, max_length=255, null=True)),
                ('numero', models.CharField(blank=True, max_length=10, null=True)),
                ('bairro', models.CharField(blank=True, max_length=255, null=True)),
                ('cidade', models.CharField(blank=True, max_length=255, null=True)),
                ('estado', models.CharField(blank=True, max_length=2, null=True)),
                ('cep', models.CharField(blank=True, max_length=10, null=True)),
                ('pais', models.CharField(blank=True, max_length=255, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Projeto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=200)),
                ('descricao', models.TextField()),
                ('link_video', models.URLField(blank=True, null=True)),
                ('logo_projeto', models.ImageField(blank=True, null=True, upload_to='inova/')),
                ('foto1', models.ImageField(blank=True, null=True, upload_to='inova/')),
                ('foto2', models.ImageField(blank=True, null=True, upload_to='inova/')),
                ('foto3', models.ImageField(blank=True, null=True, upload_to='inova/')),
                ('foto4', models.ImageField(blank=True, null=True, upload_to='inova/')),
                ('foto5', models.ImageField(blank=True, null=True, upload_to='inova/')),
                ('startup', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='projetos', to='inova.startup')),
            ],
        ),
    ]
