# Generated by Django 5.0.7 on 2024-08-15 22:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inova', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='projeto',
            name='coordenador',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='inova.administrador'),
        ),
        migrations.CreateModel(
            name='MembroProjeto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('membro', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='inova.membro')),
                ('projeto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='inova.projeto')),
            ],
        ),
    ]
