# Generated by Django 5.0.6 on 2025-09-30 22:47

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inova', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Noticia',
            fields=[
                ('id_noticia', models.AutoField(primary_key=True, serialize=False)),
                ('titulo', models.CharField(max_length=255, verbose_name='Título')),
                ('descricao', models.TextField(verbose_name='Descrição')),
                ('data_publicacao', models.DateField(default=django.utils.timezone.now, verbose_name='Data de publicação')),
                ('categoria', models.CharField(choices=[('STARTUP', 'Startups'), ('INOVACAO', 'Inovação'), ('EVENTO', 'Eventos')], max_length=20, verbose_name='Categoria')),
                ('administrador', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='noticias', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Notícia',
                'verbose_name_plural': 'Notícias',
                'ordering': ['-data_publicacao'],
            },
        ),
    ]
