# Generated by Django 5.0.6 on 2024-06-04 00:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inova', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='startup',
            name='cnpj',
            field=models.IntegerField(),
        ),
    ]
