# Generated by Django 5.0.7 on 2024-08-13 18:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inova', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Administrador',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=200)),
                ('cargo', models.CharField(max_length=100)),
                ('formacao', models.CharField(max_length=200)),
                ('email', models.EmailField(max_length=254)),
                ('linkedin', models.URLField(blank=True, null=True)),
                ('startup', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='administradores', to='inova.startup')),
            ],
        ),
        migrations.CreateModel(
            name='Membro',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=200)),
                ('cargo', models.CharField(blank=True, max_length=200, null=True)),
                ('startup', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='membros', to='inova.startup')),
            ],
        ),
        migrations.AddField(
            model_name='projeto',
            name='membros',
            field=models.ManyToManyField(related_name='projetos', to='inova.membro'),
        ),
        migrations.CreateModel(
            name='Socio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=200)),
                ('cargo', models.CharField(max_length=100)),
                ('formacao', models.CharField(max_length=200)),
                ('email', models.EmailField(max_length=254)),
                ('linkedin', models.URLField(blank=True, null=True)),
                ('startup', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='socios', to='inova.startup')),
            ],
        ),
    ]
