# Generated by Django 5.0.7 on 2024-08-13 19:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inova', '0002_administrador_membro_projeto_membros_socio'),
    ]

    operations = [
        migrations.AlterField(
            model_name='projeto',
            name='membros',
            field=models.ManyToManyField(related_name='projetos', to='inova.socio'),
        ),
        migrations.AlterField(
            model_name='socio',
            name='formacao',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='socio',
            name='nome',
            field=models.CharField(max_length=100),
        ),
    ]
