# Generated by Django 5.0.7 on 2024-08-15 23:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inova', '0002_projeto_coordenador_membroprojeto'),
    ]

    operations = [
        migrations.AlterField(
            model_name='projeto',
            name='coordenador',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='projetos_coordenados', to='inova.administrador'),
        ),
    ]
