# Generated by Django 5.0.6 on 2024-06-05 17:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inova', '0002_alter_startup_cnpj'),
    ]

    operations = [
        migrations.AddField(
            model_name='startup',
            name='logo_startup',
            field=models.ImageField(blank=True, null=True, upload_to='images/logo_startup'),
        ),
    ]
