# Generated by Django 5.0.7 on 2024-08-16 12:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inova', '0003_alter_projeto_coordenador'),
    ]

    operations = [
        migrations.AlterField(
            model_name='membroprojeto',
            name='membro',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='projetos_membro', to='inova.membro'),
        ),
        migrations.AlterField(
            model_name='membroprojeto',
            name='projeto',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='membros_projeto', to='inova.projeto'),
        ),
    ]
