# Generated by Django 5.0.7 on 2024-08-14 11:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inova', '0003_alter_projeto_membros_alter_socio_formacao_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='membro',
            name='startup',
        ),
        migrations.AddField(
            model_name='membro',
            name='email',
            field=models.EmailField(default='Não_valido@example.com', max_length=254),
        ),
        migrations.AddField(
            model_name='membro',
            name='formacao',
            field=models.CharField(default='Exemplo: Segundo Grau', max_length=255),
        ),
        migrations.AddField(
            model_name='membro',
            name='linkedin',
            field=models.URLField(blank=True, default='www.linkedin.com/', null=True),
        ),
        migrations.AddField(
            model_name='membro',
            name='startups',
            field=models.ManyToManyField(blank=True, related_name='membros', to='inova.startup'),
        ),
        migrations.AlterField(
            model_name='administrador',
            name='cargo',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='administrador',
            name='formacao',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='administrador',
            name='nome',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='administrador',
            name='startup',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='administrador', to='inova.startup'),
        ),
        migrations.AlterField(
            model_name='membro',
            name='cargo',
            field=models.CharField(default='TI', max_length=255),
        ),
        migrations.AlterField(
            model_name='membro',
            name='nome',
            field=models.CharField(default='Fulano', max_length=255),
        ),
    ]
