# Generated by Django 5.0.6 on 2024-06-07 14:46

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("inova", "0003_startup_logo_startup"),
    ]

    operations = [
        migrations.AlterField(
            model_name="startup",
            name="logo_startup",
            field=models.ImageField(blank=True, null=True, upload_to="inova/"),
        ),
    ]
