# Generated by Django 5.0.6 on 2025-09-30 23:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inova', '0003_noticia_imagem'),
    ]

    operations = [
        migrations.AddField(
            model_name='noticia',
            name='link',
            field=models.URLField(blank=True, max_length=500, null=True, verbose_name='Link da notícia'),
        ),
    ]
