# Generated by Django 5.2.6 on 2025-10-07 23:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inova', '0004_noticia_link'),
    ]

    operations = [
        migrations.CreateModel(
            name='LinkFormulario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('link', models.URLField(max_length=500, verbose_name='Link do Formulário')),
                ('data', models.DateTimeField(auto_now=True, verbose_name='Data de Atualização')),
            ],
            options={
                'verbose_name': 'Link do Formulário',
                'verbose_name_plural': 'Links dos Formulários',
                'ordering': ['-data'],
            },
        ),
    ]
