# Generated by Django 5.0.7 on 2024-08-16 12:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inova', '0004_alter_membroprojeto_membro_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='membroprojeto',
            name='membro',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='inova.membro'),
        ),
    ]
