# Generated by Django 5.0.6 on 2024-06-07 16:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inova', '0004_alter_startup_logo_startup'),
    ]

    operations = [
        migrations.CreateModel(
            name='Noticias',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('nome', models.CharField(max_length=200)),
                ('descricao', models.TextField(default='Descricao')),
                ('imagem', models.ImageField(blank=True, null=True, upload_to='media/noticias/')),
                ('link', models.URLField(blank=True, null=True)),
            ],
        ),
    ]
