# Generated by Django 5.0.7 on 2024-08-14 12:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inova', '0004_remove_membro_startup_membro_email_membro_formacao_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='projeto',
            name='membros',
        ),
        migrations.RemoveField(
            model_name='membro',
            name='startups',
        ),
        migrations.AddField(
            model_name='membro',
            name='startup',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='membros', to='inova.startup'),
        ),
        migrations.DeleteModel(
            name='Socio',
        ),
    ]
