# Generated by Django 5.0.6 on 2024-06-07 18:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inova', '0005_noticias'),
    ]

    operations = [
        migrations.AddField(
            model_name='startup',
            name='descricao',
            field=models.TextField(default='descrição...'),
        ),
    ]
