# Generated by Django 5.0.7 on 2024-08-16 12:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inova', '0005_alter_membroprojeto_membro'),
    ]

    operations = [
        migrations.AlterField(
            model_name='membroprojeto',
            name='projeto',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='membros', to='inova.projeto'),
        ),
    ]
