# Generated by Django 5.2.6 on 2025-10-07 23:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inova', '0005_linkformulario'),
    ]

    operations = [
        migrations.AlterField(
            model_name='linkformulario',
            name='data',
            field=models.DateTimeField(verbose_name='Data de Atualização'),
        ),
    ]
