# Generated by Django 5.0.7 on 2024-08-14 12:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inova', '0005_remove_projeto_membros_remove_membro_startups_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='membro',
            name='startup',
        ),
        migrations.DeleteModel(
            name='Administrador',
        ),
        migrations.DeleteModel(
            name='Membro',
        ),
    ]
