# Generated by Django 5.0.7 on 2024-08-14 12:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inova', '0006_remove_membro_startup_delete_administrador_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Administrador',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('nome', models.CharField(max_length=200)),
                ('cargo', models.CharField(max_length=200)),
                ('formacao', models.CharField(max_length=200)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('linkedin', models.URLField(blank=True, null=True)),
                ('senha', models.CharField(max_length=128)),
                ('startup', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='administrador', to='inova.startup')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Membro',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=200)),
                ('cargo', models.CharField(max_length=200)),
                ('formacao', models.CharField(max_length=200)),
                ('email', models.EmailField(max_length=254)),
                ('linkedin', models.URLField(blank=True, null=True)),
                ('startup', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='membros', to='inova.startup')),
            ],
        ),
    ]
