# Generated by Django 5.0.6 on 2024-10-07 18:25

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("inova", "0006_alter_membroprojeto_projeto"),
    ]

    operations = [
        migrations.AddField(
            model_name="administrador",
            name="foto",
            field=models.ImageField(blank=True, null=True, upload_to="media/membros/"),
        ),
        migrations.AddField(
            model_name="membro",
            name="foto",
            field=models.ImageField(blank=True, null=True, upload_to="media/membros/"),
        ),
        migrations.AlterField(
            model_name="startup",
            name="cnpj",
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name="startup",
            name="telefone",
            field=models.CharField(max_length=200),
        ),
    ]
