# Generated by Django 5.0.6 on 2024-06-17 22:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inova', '0006_startup_descricao'),
    ]

    operations = [
        migrations.AddField(
            model_name='startup',
            name='bairro',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='startup',
            name='cep',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='startup',
            name='cidade',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='startup',
            name='estado',
            field=models.CharField(blank=True, max_length=2, null=True),
        ),
        migrations.AddField(
            model_name='startup',
            name='numero',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='startup',
            name='pais',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='startup',
            name='rua',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
