# Generated by Django 5.2.6 on 2025-10-11 18:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inova', '0006_alter_linkformulario_data'),
    ]

    operations = [
        migrations.AlterField(
            model_name='linkformulario',
            name='data',
            field=models.DateTimeField(auto_now=True, verbose_name='Data de Atualização'),
        ),
    ]
