# Generated by Django 5.0.7 on 2024-08-14 12:58

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inova', '0007_administrador_membro'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='administrador',
            name='last_login',
        ),
        migrations.RemoveField(
            model_name='administrador',
            name='password',
        ),
        migrations.AddField(
            model_name='administrador',
            name='user',
            field=models.OneToOneField(default=1, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='administrador',
            name='cargo',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='administrador',
            name='email',
            field=models.EmailField(max_length=254),
        ),
        migrations.AlterField(
            model_name='administrador',
            name='formacao',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='administrador',
            name='linkedin',
            field=models.URLField(default=1),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='administrador',
            name='nome',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='membro',
            name='cargo',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='membro',
            name='formacao',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='membro',
            name='linkedin',
            field=models.URLField(default=1),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='membro',
            name='nome',
            field=models.CharField(max_length=100),
        ),
    ]
