# Generated by Django 5.2.6 on 2025-10-11 20:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inova', '0007_alter_linkformulario_data'),
    ]

    operations = [
        migrations.CreateModel(
            name='CategoriaNoticia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=50, unique=True, verbose_name='Nome da categoria')),
                ('descricao', models.TextField(blank=True, null=True, verbose_name='Descrição')),
                ('ativa', models.BooleanField(default=True, verbose_name='Ativa')),
                ('data_criacao', models.DateTimeField(auto_now_add=True, verbose_name='Data de criação')),
            ],
            options={
                'verbose_name': 'Categoria de Notícia',
                'verbose_name_plural': 'Categorias de Notícias',
                'ordering': ['nome'],
            },
        ),
    ]
