# Generated by Django 5.0.6 on 2024-08-02 01:19

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("inova", "0008_noticias_data_projeto"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="noticias",
            name="data",
        ),
    ]
