# Generated by Django 5.2.6 on 2025-10-11 20:43

from django.db import migrations


def popular_categorias_iniciais(apps, schema_editor):
    """Popula o banco com as categorias iniciais."""
    CategoriaNoticia = apps.get_model('inova', 'CategoriaNoticia')
    
    categorias_iniciais = [
        {
            'nome': 'Startups',
            'descricao': 'Notícias relacionadas a startups e empreendedorismo',
            'ativa': True
        },
        {
            'nome': 'Inovação',
            'descricao': 'Notícias sobre inovação e tecnologia',
            'ativa': True
        },
        {
            'nome': 'Eventos',
            'descricao': 'Notícias sobre eventos e atividades',
            'ativa': True
        },
        {
            'nome': 'Pesquisa',
            'descricao': 'Notícias sobre pesquisas e descobertas científicas',
            'ativa': True
        },
        {
            'nome': 'Ensino',
            'descricao': 'Notícias sobre ensino e educação',
            'ativa': True
        }
    ]
    
    for categoria_data in categorias_iniciais:
        categoria, created = CategoriaNoticia.objects.get_or_create(
            nome=categoria_data['nome'],
            defaults=categoria_data
        )
        if created:
            print(f"Categoria '{categoria_data['nome']}' criada com sucesso.")


def reverter_popular_categorias(apps, schema_editor):
    """Remove as categorias criadas pela migração."""
    CategoriaNoticia = apps.get_model('inova', 'CategoriaNoticia')
    nomes_categorias = ['Startups', 'Inovação', 'Eventos', 'Pesquisa', 'Ensino']
    CategoriaNoticia.objects.filter(nome__in=nomes_categorias).delete()


class Migration(migrations.Migration):

    dependencies = [
        ('inova', '0008_categorianoticia'),
    ]

    operations = [
        migrations.RunPython(
            popular_categorias_iniciais,
            reverter_popular_categorias
        ),
    ]
