# Generated by Django 5.2.6 on 2025-10-11 20:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inova', '0009_popular_categorias_iniciais'),
    ]

    operations = [
        migrations.DeleteModel(
            name='CategoriaNoticia',
        ),
    ]
