# Generated by Django 5.0.6 on 2024-08-02 01:24

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("inova", "0009_remove_noticias_data"),
    ]

    operations = [
        migrations.AlterModelTable(
            name="projeto",
            table="inova_projeto",
        ),
    ]
