# Generated by Django 5.0.6 on 2025-10-19 03:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inova', '0010_delete_categorianoticia'),
    ]

    operations = [
        migrations.AlterField(
            model_name='noticia',
            name='categoria',
            field=models.CharField(choices=[('STARTUP', 'Startups'), ('INOVACAO', 'Inovação'), ('EVENTO', 'Eventos'), ('PESQUISA', 'Pesquisa'), ('TECNOLOGIA', 'Tecnologia'), ('INSTITUCIONAL', 'Institucional'), ('OUTROS', 'Outros')], max_length=20, verbose_name='Categoria'),
        ),
        migrations.AlterField(
            model_name='startup',
            name='tamanho_equipe',
            field=models.CharField(default=0, verbose_name='Tamanho da Equipe'),
        ),
    ]
