# Generated by Django 5.0.6 on 2024-08-02 01:28

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("inova", "0010_alter_projeto_table"),
    ]

    operations = [
        migrations.AlterModelTable(
            name="projeto",
            table=None,
        ),
    ]
