# Generated by Django 5.0.6 on 2024-08-02 01:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inova', '0008_projeto'),
        ('inova', '0011_alter_projeto_table'),
    ]

    operations = [
    ]
