# Generated by Django 4.2.25 on 2025-10-22 21:43

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('inova', '0011_alter_noticia_categoria_alter_startup_tamanho_equipe'),
    ]

    operations = [
        migrations.AddField(
            model_name='startup',
            name='data_criacao',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='Data de Criação'),
        ),
    ]
