# Generated by Django 5.2.6 on 2025-10-29 16:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inova', '0012_startup_data_criacao'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='linkformulario',
            options={'ordering': ['-data'], 'verbose_name': 'Link do Formulário', 'verbose_name_plural': 'Link do Formulário'},
        ),
    ]
