# Generated by Django 5.0.6 on 2024-08-02 01:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inova', '0012_merge_0008_projeto_0011_alter_projeto_table'),
    ]

    operations = [
        migrations.AddField(
            model_name='projeto',
            name='logo_projeto',
            field=models.ImageField(blank=True, null=True, upload_to='inova/'),
        ),
    ]
