# Generated by Django 5.0.6 on 2024-08-02 02:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inova', '0015_projeto_logo_projeto'),
    ]

    operations = [
        migrations.AlterField(
            model_name='projeto',
            name='logo_projeto',
            field=models.ImageField(blank=True, null=True, upload_to='logos/'),
        ),
    ]
