# Generated by Django 5.0.6 on 2024-08-02 02:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inova', '0016_alter_projeto_logo_projeto'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='projeto',
            name='logo_projeto',
        ),
    ]
