# Generated by Django 5.0.6 on 2024-08-02 17:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inova', '0017_remove_projeto_logo_projeto'),
    ]

    operations = [
        migrations.AddField(
            model_name='projeto',
            name='logo_projeto',
            field=models.ImageField(blank=True, null=True, upload_to='inova/'),
        ),
    ]
