# Generated by Django 5.0.6 on 2024-08-02 23:42

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("inova", "0018_projeto_logo_projeto"),
    ]

    operations = [
        migrations.AddField(
            model_name="noticias",
            name="data",
            field=models.DateField(
                auto_now_add=True, default=django.utils.timezone.now
            ),
            preserve_default=False,
        ),
    ]
