# Generated by Django 5.0.6 on 2024-08-03 00:59

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("inova", "0019_noticias_data"),
    ]

    operations = [
        migrations.AlterField(
            model_name="noticias",
            name="data",
            field=models.DateField(),
        ),
    ]
