# Generated by Django 5.0.6 on 2024-08-03 16:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inova', '0020_alter_noticias_data'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProjetoImagem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('imagem', models.ImageField(upload_to='inova/')),
                ('projeto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='imagens', to='inova.projeto')),
            ],
        ),
    ]
