# Generated by Django 5.0.6 on 2024-08-03 16:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inova', '0021_projetoimagem'),
    ]

    operations = [
        migrations.AddField(
            model_name='projeto',
            name='foto1',
            field=models.ImageField(blank=True, null=True, upload_to='inova/'),
        ),
        migrations.AddField(
            model_name='projeto',
            name='foto2',
            field=models.ImageField(blank=True, null=True, upload_to='inova/'),
        ),
        migrations.AddField(
            model_name='projeto',
            name='foto3',
            field=models.ImageField(blank=True, null=True, upload_to='inova/'),
        ),
        migrations.DeleteModel(
            name='ProjetoImagem',
        ),
    ]
