# Generated by Django 5.0.6 on 2024-08-03 18:26

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("inova", "0022_projeto_foto1_projeto_foto2_projeto_foto3_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="projeto",
            name="foto4",
            field=models.ImageField(blank=True, null=True, upload_to="inova/"),
        ),
        migrations.AddField(
            model_name="projeto",
            name="foto5",
            field=models.ImageField(blank=True, null=True, upload_to="inova/"),
        ),
    ]
